language: python
python: 3.7

jobs:
  include:
    - if: branch = master
      env: TOXENV=py37-master
      after_success: codecov
    - if: branch != master
      env: TOXENV=py37-dev
      after_success: codecov
    - env: TOXENV=build
    - env: TOXENV=pre-commit

install:
  - pip install tox
  - pip install codecov

script: tox
