language: python
python:
- '2.7'

before_install:
    - pip install coveralls
    - pip install -r test_requirements.txt --extra-index-url https://testpypi.python.org/pypi

install:
    - pip install -r requirements.txt --extra-index-url https://testpypi.python.org/pypi
    - python setup.py install

script:
    - python runtests.py --with-coverage  --cover-package=cloudshell
    - python setup.py develop
    - python setup.py sdist --format zip

after_success:
    - coveralls
